# Generated by OpenClaw
# pytest configuration for methodology-v2
#
# This file allows pytest to run tests from within the project directory
# by properly configuring sys.path and avoiding __init__.py relative import issues

import sys
from pathlib import Path

# Add project root to path FIRST (before any project imports)
project_root = Path(__file__).parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

# Import enforcement modules directly (avoiding __init__.py)
import importlib.util

def load_module_direct(name, path):
    """Load a module directly from path, bypassing package __init__"""
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module

# Pre-load enforcement modules to avoid __init__.py issues
enforcement_path = project_root / "enforcement"
for py_file in enforcement_path.glob("*.py"):
    if py_file.name != "__init__.py":
        module_name = f"enforcement.{py_file.stem}"
        try:
            load_module_direct(module_name, py_file)
        except:
            pass

import pytest

def pytest_configure(config):
    """Configure pytest"""
    # Suppress warnings about package imports
    config.option.pythonwarnings = ["ignore::ImportWarning"]
