#!/usr/bin/env python3
"""
Framework Bridge - CrewAI ↔ LangGraph Migration

提供 CrewAI 和 LangGraph 之間的雙向遷移能力。
"""

import ast
import re
import json
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Tuple, Set
from enum import Enum


class BridgeFramework(Enum):
    """目標框架"""
    CREWAI = "crewai"
    LANGGRAPH = "langgraph"


@dataclass
class CrewAIAgent:
    """CrewAI Agent 結構"""
    name: str
    role: str
    goal: str
    backstory: str
    tools: List[str] = field(default_factory=list)
    llm: str = ""
    verbose: bool = False
    allow_delegation: bool = False


@dataclass
class CrewAITask:
    """CrewAI Task 結構"""
    description: str
    agent: str
    expected_output: str = ""


@dataclass
class CrewAIFlow:
    """CrewAI Flow 結構"""
    agents: List[CrewAIAgent] = field(default_factory=list)
    tasks: List[CrewAITask] = field(default_factory=list)
    process: str = "sequential"  # sequential, parallel, hierarchical


@dataclass
class MigrationReport:
    """遷移報告"""
    source_framework: str
    target_framework: str
    original_file: str
    output_file: str
    success: bool
    nodes_migrated: int = 0
    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    generated_code: str = ""


class FrameworkBridge:
    """框架遷移橋接器 - CrewAI ↔ LangGraph"""

    def __init__(self):
        self.migration_history: List[MigrationReport] = []

    # ==================== CREWAI → LANGGRAPH ====================

    def crewai_to_langgraph(self, crewai_flow: Any) -> str:
        """
        將 CrewAI Flow 轉換為 LangGraph

        Args:
            crewai_flow: CrewAIFlow 物件或 crewai .py 檔案路徑

        Returns:
            LangGraph Python 代碼字串
        """
        if isinstance(crewai_flow, str):
            # 如果是檔案路徑，先解析
            crewai_flow = self._parse_crewai_file(crewai_flow)

        return self._generate_langgraph_from_crewai(crewai_flow)

    def _parse_crewai_file(self, file_path: str) -> 'CrewAIFlow':
        """解析 CrewAI Python 檔案"""
        with open(file_path, 'r') as f:
            source = f.read()

        flow = CrewAIFlow()

        # 解析 agents
        agent_pattern = r'Agent\s*\(\s*([^)]+)\)'
        agents = re.findall(agent_pattern, source)
        for agent_def in agents:
            agent = self._parse_agent_definition(agent_def)
            if agent:
                flow.agents.append(agent)

        # 解析 tasks
        task_pattern = r'Task\s*\(\s*([^)]+)\)'
        tasks = re.findall(task_pattern, source)
        for task_def in tasks:
            task = self._parse_task_definition(task_def, source)
            if task:
                flow.tasks.append(task)

        # 解析 process 模式
        process_match = re.search(r'process\s*=\s*["\'](\w+)["\']', source)
        if process_match:
            flow.process = process_match.group(1)

        return flow

    def _parse_agent_definition(self, agent_def: str) -> Optional[CrewAIAgent]:
        """解析 Agent 定義"""
        name_match = re.search(r'role\s*=\s*["\']([^"\']+)["\']', agent_def)
        role_match = re.search(r'role\s*=\s*["\']([^"\']+)["\']', agent_def)
        goal_match = re.search(r'goal\s*=\s*["\']([^"\']+)["\']', agent_def)
        backstory_match = re.search(r'backstory\s*=\s*["\']([^"\']+)["\']', agent_def)

        if not role_match:
            return None

        name = role_match.group(1).split()[-1] if role_match else "UnknownAgent"

        return CrewAIAgent(
            name=name,
            role=role_match.group(1) if role_match else "",
            goal=goal_match.group(1) if goal_match else "",
            backstory=backstory_match.group(1) if backstory_match else "",
        )

    def _parse_task_definition(self, task_def: str, source: str) -> Optional[CrewAITask]:
        """解析 Task 定義"""
        desc_match = re.search(r'description\s*=\s*["\']([^"\']+)["\']', task_def)
        expected_match = re.search(r'expected_output\s*=\s*["\']([^"\']+)["\']', task_def)

        if not desc_match:
            return None

        return CrewAITask(
            description=desc_match.group(1),
            agent="",  # 需要從 source 中找 agent
            expected_output=expected_match.group(1) if expected_match else "",
        )

    def _generate_langgraph_from_crewai(self, flow: CrewAIFlow) -> str:
        """從 CrewAI Flow 生成 LangGraph 代碼"""
        lines = []
        lines.append("# Migrated from CrewAI to LangGraph")
        lines.append("# Generated by FrameworkBridge")
        lines.append("")

        # Imports
        lines.append("from typing import TypedDict, Annotated, List, Literal")
        lines.append("from langgraph.graph import StateGraph, END, START")
        lines.append("from langchain_core.messages import HumanMessage, BaseMessage, SystemMessage")
        lines.append("from langchain_openai import ChatOpenAI")
        lines.append("")

        # State definition
        lines.append("# State Definition")
        lines.append("class State(TypedDict):")
        lines.append("    messages: List[BaseMessage]")
        lines.append("    current_task: str")
        lines.append("    context: dict")
        lines.append("    task_results: dict")
        lines.append("")

        # Generate agent nodes
        lines.append("# Agent Nodes")
        for agent in flow.agents:
            agent_name_safe = agent.name.lower().replace(" ", "_")
            lines.append(f"\ndef {agent_name_safe}_agent(state: State) -> State:")
            lines.append(f'    """Agent: {agent.role}"""')
            if agent.goal:
                lines.append(f'    # Goal: {agent.goal}')
            lines.append("    llm = ChatOpenAI(model='gpt-4')")
            lines.append("    system_msg = SystemMessage(content=f\"You are {agent.role}. {agent.goal}\")")
            lines.append("    messages = [system_msg] + state.get('messages', [])")
            lines.append("    response = llm.invoke(messages)")
            lines.append("    state['messages'] = state.get('messages', []) + [response]")
            lines.append("    return state")

        lines.append("")

        # Build graph
        lines.append("# Build Graph")
        lines.append("def build_crew_graph():")
        lines.append("    graph = StateGraph(State)")
        lines.append("")
        lines.append("    # Add nodes")
        for agent in flow.agents:
            agent_name_safe = agent.name.lower().replace(" ", "_")
            lines.append(f'    graph.add_node("{agent.name}", {agent_name_safe}_agent)')
        lines.append("")

        # Add edges based on process type
        if flow.process == "sequential":
            lines.append("    # Sequential process")
            if flow.agents:
                lines.append(f'    graph.add_edge(START, "{flow.agents[0].name}")')
                for i in range(len(flow.agents) - 1):
                    lines.append(f'    graph.add_edge("{flow.agents[i].name}", "{flow.agents[i+1].name}")')
                lines.append(f'    graph.add_edge("{flow.agents[-1].name}", END)')
        elif flow.process == "parallel":
            lines.append("    # Parallel process")
            lines.append("    graph.add_edge(START, END)")
        else:
            lines.append("    # Hierarchical process")
            lines.append(f'    graph.add_edge(START, "{flow.agents[0].name}")')
            lines.append(f'    graph.add_edge("{flow.agents[-1].name}", END)')

        lines.append("")
        lines.append("    return graph.compile()")

        lines.append("")
        lines.append("# Usage")
        lines.append("if __name__ == '__main__':")
        lines.append("    crew_graph = build_crew_graph()")
        lines.append("    initial_state = {")
        lines.append("        'messages': [HumanMessage(content='Start the crew task')],")
        lines.append("        'current_task': '',")
        lines.append("        'context': {},")
        lines.append("        'task_results': {}")
        lines.append("    }")
        lines.append("    result = crew_graph.invoke(initial_state)")
        lines.append("    print(result)")

        return "\n".join(lines)

    def export_crewai_to_file(self, crewai_file: str, output_file: str = None) -> MigrationReport:
        """匯出 CrewAI 檔案為 LangGraph"""
        if output_file is None:
            output_file = crewai_file.replace(".py", "_migrated_to_langgraph.py")

        try:
            langgraph_code = self.crewai_to_langgraph(crewai_file)

            report = MigrationReport(
                source_framework="crewai",
                target_framework="langgraph",
                original_file=crewai_file,
                output_file=output_file,
                success=True,
                generated_code=langgraph_code
            )

            # 嘗試計算節點數
            flow = self._parse_crewai_file(crewai_file)
            report.nodes_migrated = len(flow.agents)

            with open(output_file, 'w') as f:
                f.write(langgraph_code)

        except Exception as e:
            report = MigrationReport(
                source_framework="crewai",
                target_framework="langgraph",
                original_file=crewai_file,
                output_file=output_file,
                success=False,
                errors=[str(e)]
            )

        self.migration_history.append(report)
        return report

    # ==================== LANGGRAPH → CREWAI ====================

    def langgraph_to_crewai(self, langgraph_file: str) -> str:
        """
        將 LangGraph 轉換為 CrewAI

        Args:
            langgraph_file: LangGraph .py 檔案路徑

        Returns:
            CrewAI Python 代碼字串
        """
        with open(langgraph_file, 'r') as f:
            source = f.read()

        return self._generate_crewai_from_langgraph(source)

    def _generate_crewai_from_langgraph(self, source: str) -> str:
        """從 LangGraph 源碼生成 CrewAI 代碼"""
        lines = []
        lines.append("# Migrated from LangGraph to CrewAI")
        lines.append("# Generated by FrameworkBridge")
        lines.append("")
        lines.append("from crewai import Agent, Task, Crew, Process")
        lines.append("from langchain_openai import ChatOpenAI")
        lines.append("")

        # Extract nodes (functions that return State)
        node_pattern = r'def\s+(\w+)\s*\([^)]*state[^)]*\)\s*(?:->\s*State)?:'
        nodes = re.findall(node_pattern, source)

        # Extract state fields
        state_pattern = r'class\s+State\s*\(TypedDict\):\s*\n((?:.*\n)*?)(?=\nclass|\ndef|\Z)'
        state_match = re.search(state_pattern, source)

        # Generate agents
        lines.append("# Agents")
        agent_names = set()

        for node in nodes:
            if node.endswith('_agent') or 'agent' in node.lower():
                agent_name = node.replace('_agent', '').title().replace('_', '')
                agent_names.add(agent_name)
                lines.append(f"{agent_name.lower()}_agent = Agent(")
                lines.append(f'    role="{agent_name} Agent",')
                lines.append(f'    goal=f"Your goal as {agent_name} agent",')
                lines.append(f'    backstory="You are a dedicated {agent_name} agent",')
                lines.append(f'    verbose=True,')
                lines.append(f'    llm=ChatOpenAI(model="gpt-4")')
                lines.append(")")
                lines.append("")

        # If no agents found, create a default one
        if not agent_names:
            lines.append("default_agent = Agent(")
            lines.append('    role="Default Agent",')
            lines.append('    goal="Complete the assigned task",')
            lines.append('    backstory="You are a helpful AI agent",')
            lines.append('    verbose=True,')
            lines.append('    llm=ChatOpenAI(model="gpt-4")')
            lines.append(")")
            lines.append("")

        # Generate tasks
        lines.append("# Tasks")
        lines.append("task1 = Task(")
        lines.append('    description="Execute the workflow task",')
        lines.append(f'    agent={list(agent_names)[0].lower() + "_agent" if agent_names else "default_agent"},')
        lines.append('    expected_output="Task completion result"')
        lines.append(")")
        lines.append("")

        # Generate crew
        lines.append("# Crew")
        agent_list = ", ".join([f"{a.lower()}_agent" for a in agent_names]) or "default_agent"
        lines.append(f"crew = Crew(")
        lines.append(f"    agents=[{agent_list}],")
        lines.append("    tasks=[task1],")
        lines.append("    process=Process.sequential")
        lines.append(")")
        lines.append("")
        lines.append("# Kickoff")
        lines.append("result = crew.kickoff()")
        lines.append("print(result)")

        return "\n".join(lines)

    def export_langgraph_to_crewai_file(self, langgraph_file: str, output_file: str = None) -> MigrationReport:
        """匯出 LangGraph 檔案為 CrewAI"""
        if output_file is None:
            output_file = langgraph_file.replace(".py", "_migrated_to_crewai.py")

        try:
            crewai_code = self.langgraph_to_crewai(langgraph_file)

            report = MigrationReport(
                source_framework="langgraph",
                target_framework="crewai",
                original_file=langgraph_file,
                output_file=output_file,
                success=True,
                generated_code=crewai_code
            )

            # 嘗試計算節點數
            source = open(langgraph_file).read()
            node_pattern = r'def\s+(\w+)\s*\([^)]*state[^)]*\)\s*(?:->\s*State)?:'
            nodes = re.findall(node_pattern, source)
            report.nodes_migrated = len(nodes)

            with open(output_file, 'w') as f:
                f.write(crewai_code)

        except Exception as e:
            report = MigrationReport(
                source_framework="langgraph",
                target_framework="crewai",
                original_file=langgraph_file,
                output_file=output_file,
                success=False,
                errors=[str(e)]
            )

        self.migration_history.append(report)
        return report

    # ==================== VALIDATION ====================

    def validate_migration(self, original_file: str, converted_file: str, direction: str) -> Tuple[bool, List[str]]:
        """
        驗證遷移正確性

        Args:
            original_file: 原始檔案路徑
            converted_file: 轉換後檔案路徑
            direction: "crewai_to_langgraph" 或 "langgraph_to_crewai"

        Returns:
            (success, messages) - 驗證是否成功及訊息列表
        """
        messages = []

        try:
            # 檢查檔案是否存在
            if not original_file:
                messages.append("❌ Original file not found")
                return False, messages

            if not converted_file:
                messages.append("❌ Converted file not found")
                return False, messages

            # 嘗試解析 converted file 語法
            with open(converted_file, 'r') as f:
                converted_source = f.read()

            try:
                ast.parse(converted_source)
                messages.append("✅ Converted file has valid Python syntax")
            except SyntaxError as e:
                messages.append(f"❌ Syntax error in converted file: {e}")
                return False, messages

            # 檢查關鍵 import
            if direction == "crewai_to_langgraph":
                required = ["langgraph", "StateGraph", "TypedDict"]
                for req in required:
                    if req.lower() in converted_source.lower():
                        messages.append(f"✅ Found LangGraph component: {req}")
                    else:
                        messages.append(f"⚠️ Missing expected LangGraph component: {req}")

            elif direction == "langgraph_to_crewai":
                required = ["crewai", "Agent", "Task", "Crew"]
                for req in required:
                    if req.lower() in converted_source.lower():
                        messages.append(f"✅ Found CrewAI component: {req}")
                    else:
                        messages.append(f"⚠️ Missing expected CrewAI component: {req}")

            # 檢查節點數量
            orig_source = open(original_file).read()
            if direction == "crewai_to_langgraph":
                orig_nodes = len(re.findall(r'Agent\s*\(', orig_source))
                conv_nodes = len(re.findall(r'def\s+\w+_agent', converted_source))
                if orig_nodes == conv_nodes:
                    messages.append(f"✅ Agent count preserved: {orig_nodes}")
                else:
                    messages.append(f"⚠️ Agent count changed: {orig_nodes} → {conv_nodes}")
            else:
                orig_nodes = len(re.findall(r'def\s+\w+\s*\([^)]*state[^)]*\)', orig_source))
                conv_agents = len(re.findall(r'\w+_agent\s*=\s*Agent\s*\(', converted_source))
                if orig_nodes == conv_agents:
                    messages.append(f"✅ Node count preserved: {orig_nodes}")
                else:
                    messages.append(f"⚠️ Node count changed: {orig_nodes} → {conv_agents}")

            return True, messages

        except Exception as e:
            messages.append(f"❌ Validation error: {e}")
            return False, messages

    def generate_bridge_report(self, report: MigrationReport) -> str:
        """產生橋接遷移報告"""
        lines = []
        icon = "✅" if report.success else "❌"

        lines.append(f"{icon} Migration Report: {report.original_file}")
        lines.append(f"   {report.source_framework.upper()} → {report.target_framework.upper()}")
        lines.append(f"   Output: {report.output_file}")
        lines.append(f"   Nodes migrated: {report.nodes_migrated}")

        if report.warnings:
            lines.append("   Warnings:")
            for w in report.warnings:
                lines.append(f"   - {w}")

        if report.errors:
            lines.append("   Errors:")
            for e in report.errors:
                lines.append(f"   - {e}")

        return "\n".join(lines)


# ==================== Quick Bridge Helpers ====================

def bridge_quick_convert(input_file: str, from_framework: str, to_framework: str) -> MigrationReport:
    """
    快速轉換介面

    Args:
        input_file: 輸入檔案
        from_framework: "crewai" 或 "langgraph"
        to_framework: "crewai" 或 "langgraph"

    Returns:
        MigrationReport
    """
    bridge = FrameworkBridge()

    if from_framework == "crewai" and to_framework == "langgraph":
        return bridge.export_crewai_to_file(input_file)
    elif from_framework == "langgraph" and to_framework == "crewai":
        return bridge.export_langgraph_to_crewai_file(input_file)
    else:
        return MigrationReport(
            source_framework=from_framework,
            target_framework=to_framework,
            original_file=input_file,
            output_file="",
            success=False,
            errors=[f"Unsupported migration: {from_framework} → {to_framework}"]
        )


# ==================== Main ====================

if __name__ == "__main__":
    print("FrameworkBridge - CrewAI ↔ LangGraph Migration Tool")
    print("=" * 50)

    bridge = FrameworkBridge()

    # 顯示說明
    print("\nSupported migrations:")
    print("  crewai     → langgraph")
    print("  langgraph  → crewai")
    print("\nUsage:")
    print("  bridge_quick_convert('my_crewai.py', 'crewai', 'langgraph')")
    print("  bridge_quick_convert('my_langgraph.py', 'langgraph', 'crewai')")
