#!/usr/bin/env python3
"""
decision_gate_report.py - Phase 7 Decision Gate Report Generator
[FR-04] Generate Decision Gate reports for Phase 7
"""

from pathlib import Path
from typing import List
from datetime import datetime

from ..engine.engine import DecisionGateResult


class DecisionGateReportGenerator:
    """
    [FR-04] Generate Phase 7 Decision Gate reports
    
    Evaluates whether project can proceed to next phase.
    """
    
    def __init__(self, project_root: str):
        self.project_root = Path(project_root)
    
    def generate(self, result: DecisionGateResult, next_phase: int) -> str:
        """
        生成決策門報告
        
        Args:
            result: DecisionGateResult from engine.evaluate_gates()
            next_phase: Next phase number
            
        Returns:
            Report content as string
        """
        lines = [
            "# Phase 7 Decision Gate Report",
            "",
            f"**Generated**: {result.assessed_at.strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Assessment**: Entering Phase {next_phase}",
            "",
            "---",
            "",
            f"## Decision: {self._status_badge(result.status)}",
            "",
        ]
        
        # Summary
        if result.can_proceed and not result.blockers:
            lines.extend([
                "✅ **Project can proceed to next phase**",
                "",
                "All risk gates have been satisfied.",
                "",
            ])
        elif result.conditions:
            lines.extend([
                "⚠️ **Conditional Pass**",
                "",
                "Project may proceed with conditions:",
                "",
            ])
            for cond in result.conditions:
                lines.append(f"- {cond}")
            lines.append("")
        else:
            lines.extend([
                "❌ **BLOCKED**",
                "",
                "Project cannot proceed until the following are resolved:",
                "",
            ])
            for blocker in result.blockers:
                lines.append(f"- {blocker}")
            lines.append("")
        
        # Blockers (if any)
        if result.blockers:
            lines.extend([
                "### 🔴 Blockers",
                "",
            ])
            for blocker in result.blockers:
                lines.append(f"- {blocker}")
            lines.append("")
        
        # Conditions (if any)
        if result.conditions:
            lines.extend([
                "### 🟡 Conditions",
                "",
            ])
            for cond in result.conditions:
                lines.append(f"- {cond}")
            lines.append("")
        
        # Recommendations
        if result.recommendations:
            lines.extend([
                "### 💡 Recommendations",
                "",
            ])
            for rec in result.recommendations:
                lines.append(f"- {rec}")
            lines.append("")
        
        # Risk Summary
        lines.extend([
            "---",
            "",
            "## Risk Context",
            "",
        ])
        
        # Get risk summary from tracker
        try:
            from ..engine.tracker import RiskTracker
            tracker = RiskTracker(str(self.project_root))
            summary = tracker.export_to_register()
            
            lines.extend([
                f"- **Total Risks**: {summary['total']}",
                f"- **Open**: {summary['open']}",
                f"- **Closed**: {summary['closed']}",
                "",
                "### By Level",
                f"- Critical: {summary['by_level'].get('critical', 0)}",
                f"- High: {summary['by_level'].get('high', 0)}",
                f"- Medium: {summary['by_level'].get('medium', 0)}",
                f"- Low: {summary['by_level'].get('low', 0)}",
                "",
            ])
        except Exception as e:
            lines.append(f"_Error loading risk summary: {e}_")
            lines.append("")
        
        # Sign-off section
        lines.extend([
            "---",
            "",
            "## Sign-off",
            "",
            "| Role | Name | Date | Decision |",
            "|------|------|------|----------|",
            "| Tech Lead | | | |",
            "| Project Manager | | | |",
            "",
            "---",
            f"*Generated by Risk Assessment Engine | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
        ])
        
        return "\n".join(lines)
    
    def _status_badge(self, status: str) -> str:
        """返回狀態標記"""
        badges = {
            "PASS": "🟢 PASS",
            "CONDITIONAL_PASS": "🟡 CONDITIONAL PASS",
            "BLOCKED": "🔴 BLOCKED",
        }
        return badges.get(status, status)
    
    def save(self, result: DecisionGateResult, next_phase: int) -> Path:
        """
        生成並保存決策門報告
        
        Args:
            result: DecisionGateResult
            next_phase: Next phase number
            
        Returns:
            Path to saved report
        """
        content = self.generate(result, next_phase)
        
        filename = f"Phase7_DecisionGate_Report.md"
        output_path = self.project_root / filename
        
        output_path.write_text(content, encoding="utf-8")
        
        return output_path