#!/usr/bin/env python3
"""
Agent-Proof Hook
================
讓 Agent 無法繞過的 Hook

特點：
1. 放在 .git/hooks/ 之外（不容易被發現或刪除）
2. 核心邏輯在 Python module 中
3. Hook 只是簡單的 wrapper
4. 可設定 Unix 層面的 immutable 屬性
5. 定期檢查 Hook 是否被修改
"""

import os
import sys
import hashlib
import shutil
from pathlib import Path
from typing import Optional

class AgentProofHook:
    """
    Agent-Proof Hook
    
    使用方式：
    
    ```python
    # 安裝
    hook = AgentProofHook()
    hook.install()
    
    # 驗證
    hook.verify()  # 檢查是否被篡改
    ```
    """
    
    # Hook 放在專案根目錄的 .methodology/ 下，不在 .git/hooks/
    METHODOLOGY_DIR = ".methodology"
    HOOK_MODULE = "agent_hook_core"
    HOOK_FILE = f".methodology/{HOOK_MODULE}.py"
    
    # Hook wrapper 內容
    WRAPPER_TEMPLATE = '''#!/usr/bin/env python3
"""
Agent-Proof Pre-Commit Hook
Generated by methodology-v2
DO NOT EDIT - CHANGES WILL BE OVERWRITTEN
"""
import sys
import os

# 確保 .methodology 在 path 中
methodology_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '.methodology')
if methodology_dir not in sys.path:
    sys.path.insert(0, methodology_dir)

# 執行核心檢查
from agent_hook_core import enforce

try:
    enforce()
    print("✅ Agent-Proof Hook: All checks passed")
except SystemExit as e:
    sys.exit(e.code)
except Exception as e:
    print(f"❌ Agent-Proof Hook error: {{e}}")
    sys.exit(1)
'''
    
    def __init__(self, project_root: str = None):
        self.project_root = Path(project_root) if project_root else Path.cwd()
        self.hook_path = self.project_root / ".git" / "hooks" / "pre-commit"
        self.core_path = self.project_root / self.HOOK_FILE
    
    def install(self, force: bool = False):
        """
        安裝 Agent-Proof Hook
        
        Args:
            force: 是否強制覆蓋現有 hook
        """
        print(f"🔧 Installing Agent-Proof Hook...")
        
        # 1. 建立 .methodology 目錄
        method_dir = self.project_root / self.METHODOLOGY_DIR
        method_dir.mkdir(exist_ok=True)
        
        # 2. 複製核心模組
        self._install_core_module(method_dir)
        
        # 3. 建立/更新 git hook wrapper
        self._install_hook_wrapper(force=force)
        
        # 4. 嘗試設定 immutable（Unix 層面）
        self._try_immutable()
        
        print(f"✅ Agent-Proof Hook installed")
        print(f"   Core module: {self.core_path}")
        print(f"   Hook: {self.hook_path}")
    
    def _install_core_module(self, method_dir: Path):
        """安裝核心模組"""
        # 讀取現有的 enforcement 核心
        core_content = self._generate_core_module()
        
        core_path = method_dir / f"{self.HOOK_MODULE}.py"
        with open(core_path, 'w') as f:
            f.write(core_content)
        
        print(f"   Core module written: {core_path}")
    
    def _generate_core_module(self) -> str:
        """生成核心模組內容"""
        return '''#!/usr/bin/env python3
"""
Agent Hook Core
===============
This is the core enforcement logic that cannot be easily bypassed.
It lives in .methodology/ which is less obvious than .git/hooks/
"""

import os
import re
import sys

def enforce():
    """
    Main enforcement function
    Called by the pre-commit hook wrapper
    """
    print("🔍 Agent-Proof Hook: Running checks...")
    
    # 1. Check commit message
    commit_msg_file = os.environ.get('COMMIT_MSG_FILE', '.git/COMMIT_EDITMSG')
    
    if os.path.exists(commit_msg_file):
        with open(commit_msg_file, 'r') as f:
            msg = f.read().strip()
        
        # Check for task ID
        if not re.search(r'\\[[A-Z]+-\\d+\\]', msg):
            print("❌ Commit message must include task ID (e.g., [TASK-123])")
            print(f"   Your message: {msg[:50]}...")
            sys.exit(1)
        
        print(f"   ✅ Task ID found in commit message")
    
    # 2. Check for bypass attempts
    suspicious_env = os.environ.get('GIT_COMMAND', '')
    bypass_keywords = ['--no-verify', '--bypass', '--skip-hooks']
    
    for kw in bypass_keywords:
        if kw in suspicious_env:
            print(f"❌ Suspicious bypass keyword detected: {kw}")
            sys.exit(1)
    
    # 3. All checks passed
    print("✅ All Agent-Proof checks passed")


if __name__ == "__main__":
    enforce()
'''
    
    def _install_hook_wrapper(self, force: bool = False):
        """安裝 git hook wrapper"""
        if self.hook_path.exists() and not force:
            # 備份現有 hook
            backup_path = self.hook_path.with_suffix('.backup')
            shutil.copy(self.hook_path, backup_path)
            print(f"   Backed up existing hook to {backup_path}")
        
        # 寫入新的 wrapper
        with open(self.hook_path, 'w') as f:
            f.write(self.WRAPPER_TEMPLATE)
        
        # 設定執行權限
        os.chmod(self.hook_path, 0o755)
        print(f"   Hook wrapper installed: {self.hook_path}")
    
    def _try_immutable(self):
        """嘗試設定 Unix immutable 屬性（需要 root）"""
        try:
            # Linux chattr
            os.system(f'chattr +i {self.hook_path} 2>/dev/null')
            
            # 驗證
            if os.path.exists('/usr/bin/lsattr'):
                os.system(f'lsattr {self.hook_path} 2>/dev/null')
            
            print("   ✅ Set immutable attribute (if supported)")
        except:
            pass
    
    def verify(self) -> bool:
        """
        驗證 Hook 是否被篡改
        
        Returns:
            bool: True = 正常, False = 已被篡改
        """
        if not self.hook_path.exists():
            print("❌ Hook file missing!")
            return False
        
        if not self.core_path.exists():
            print("❌ Core module missing!")
            return False
        
        # 檢查 wrapper 內容是否正確
        with open(self.hook_path, 'r') as f:
            content = f.read()
        
        if 'Agent-Proof Hook' not in content:
            print("❌ Hook content has been modified!")
            return False
        
        # 檢查 core module 內容
        with open(self.core_path, 'r') as f:
            core = f.read()
        
        if 'def enforce()' not in core:
            print("❌ Core module has been modified!")
            return False
        
        print("✅ Hook verification passed")
        return True
    
    def uninstall(self):
        """解除安裝"""
        # 移除 immutable
        try:
            os.system(f'chattr -i {self.hook_path} 2>/dev/null')
        except:
            pass
        
        # 刪除核心模組
        if self.core_path.exists():
            self.core_path.unlink()
        
        # 恢復預設 hook
        if self.hook_path.exists():
            backup = self.hook_path.with_suffix('.backup')
            if backup.exists():
                shutil.copy(backup, self.hook_path)
                backup.unlink()
            else:
                self.hook_path.unlink()
        
        print("✅ Agent-Proof Hook uninstalled")


def main():
    """CLI 入口"""
    import sys
    
    hook = AgentProofHook()
    
    if len(sys.argv) > 1:
        cmd = sys.argv[1]
        
        if cmd == "install":
            hook.install(force=True)
        
        elif cmd == "verify":
            if not hook.verify():
                sys.exit(1)
        
        elif cmd == "uninstall":
            hook.uninstall()
        
        else:
            print(f"Unknown command: {cmd}")
            print("Available: install, verify, uninstall")
    
    else:
        hook.install()


if __name__ == "__main__":
    main()
